namespace: expedient

name: ansible_for_nsxt

version: 1.0.5

readme: README.md

authors:
- Gautam Verma @ggverma
- Rahul Raghuvanshi @r-raghu

description: Ansible Modules for NSX-t

license:
- GPL-3.0-only
- BSD-2-Clause-FreeBSD

tags: [vmware, ansible, nsxt]

dependencies: {}

repository: https://github.com/vmware/ansible-for-nsxt

documentation: https://github.com/vmware/ansible-for-nsxt

homepage: https://github.com/vmware/ansible-for-nsxt

issues: https://github.com/vmware/ansible-for-nsxt/issues

build_ignore: []
